package exceptionPrograms;

import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.Scanner;

public class Exception_Prgm2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
	
//		int aa[];
//		aa=new int[2];
//		aa[0]=18;
//		aa[1]=9;
//		for(int i=0;i<2;i++)
//		{
//			System.out.println(aa[i]);
//			
//		}
//		System.out.println(Arrays.toString(aa));
		
//		String str[]=new String[4];
//
//		System.out.println("Enter a String");
//		Scanner sc1=new Scanner(System.in);
//		for(int i=0;i<4;i++)
//		{
//		     str[i]=sc1.nextLine();
//		}
//		System.out.println("Array for string of size 4 : " +Arrays.toString(str));
		
//		String A[] = new String[4];
//		 A[0]="Atharsh";
//		 A[1]="Ash";
//		A[2]="Nikhil";
//		 A[3]="Automation";
//		for(int i=0;i<4;i++)
//		{
//		System.out.println(A[i]);
//		}
		
		
		
//		String[] name= new String[4];
//		Scanner s1=new Scanner(System.in);
//		for(int i=0;i<name.length;i++)
//		{
//		name[i]=s1.next();
//		}
//		System.out.println(name);
		
		 
	 	
//		String[] sr1= {"John", "Mega", "Swaroop", "Viswa", "Root"};
//		System.out.println(sr1.length);
		
	
		String name="Learning";
		char ch=name.charAt(4);
		System.out.println(ch);
		
//		String ref[]=new String[4];
//
//        ref[0]="20";
//        ref[1]="30";
//        ref[0]="40";
//        ref[0]="50";
//      System.out.println(ref);
		
		
	}
}
